services:
  - type: web
    name: currency-converter
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production